name: Cleanup Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"  # Runs daily at 3 AM UTC (optional)

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ROTATED_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ROTATED_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2   

      - name: Initialize Terraform
        run: |
          terraform -chdir=terraform_code/ init -reconfigure

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ vars.REGION }} --name ${{ vars.CLUSTER_NAME }}

      - name: Delete Kubernetes Resources
        run: |
          helm uninstall nginx --namespace sock-shop || true

      - name: Destroy Terraform Infrastructure
        run: |
          terraform -chdir=terraform_code/ destroy --auto-approve

      - name: Delete S3 Bucket
        run: |
          if aws s3api head-bucket --bucket "${{ vars.S3_BUCKET_NAME }}" >/dev/null 2>&1; then
            echo "Deleting S3 bucket..."
            aws s3 rb s3://${{ vars.S3_BUCKET_NAME }} --force
          else
            echo "S3 bucket does not exist, skipping."
          fi

      - name: Delete DynamoDB Table
        run: |
          if aws dynamodb describe-table --table-name "${{ vars.DYNAMODB_TABLE_NAME }}" >/dev/null 2>&1; then
            echo "Deleting DynamoDB table..."
            aws dynamodb delete-table --table-name "${{ vars.DYNAMODB_TABLE_NAME }}"
          else
            echo "DynamoDB table does not exist, skipping."
          fi

      - name: Notify Slack on Cleanup Completion
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Cleanup completed. All resources deleted."}' ${{ secrets.SLACK_WEBHOOK_URL }}
